create table schema1.Users (id  serial not null, email varchar(255), name varchar(255), primary key (id));
create index idx_user_name on schema1.Users (name);
create table schema1.Users (id  serial not null, email varchar(255), name varchar(255), primary key (id));
create index idx_user_name on schema1.Users (name);
create table schema1.Users (id  serial not null, email varchar(255), name varchar(255), primary key (id));
create index idx_user_name on schema1.Users (name);
create table schema1.Users (id  serial not null, email varchar(255), name varchar(255), primary key (id));
create index idx_user_name on schema1.Users (name);
create table schema1.Users (id  serial not null, email varchar(255), name varchar(255), primary key (id));
create index idx_user_name on schema1.Users (name);
create table schema1.Users (id  serial not null, email varchar(255), name varchar(255), primary key (id));
create index idx_user_name on schema1.Users (name);
create table schema1.Users (id  serial not null, email varchar(255), name varchar(255), primary key (id));
create index idx_user_name on schema1.Users (name);
create table schema1.Users (id  serial not null, email varchar(255), name varchar(255), primary key (id));
create index idx_user_name on schema1.Users (name);
create table schema1.Users (id  serial not null, email varchar(255), name varchar(255), primary key (id));
create index idx_user_name on schema1.Users (name);
